name: field_app
description: "Medico field-app — offline-first data entry for facility staff."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Local persistence
  sqflite: ^2.4.2+1
  path: ^1.9.1

  # HTTP client
  dio: ^5.7.0

  # Connectivity
  connectivity_plus: ^6.1.4

  # State management
  provider: ^6.1.2

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
